Switches to new ntcore artifact location
wpilibsuite/OutlineViewer pull request #39
Opened 2017-08-08 19:05 UTC by ThadHouse

2017-08-09 16:16 UTC, AustinShalit requested changes

2017-08-09 16:16 UTC, AustinShalit commented on build.gradle
> +    runtime "edu.wpi.first.ntcore:ntcore-jni:+:all"
We should separate compile and runtime dependencies into 2 sections.

2017-08-09 21:45 UTC, ThadHouse commented on build.gradle
> +    runtime "edu.wpi.first.ntcore:ntcore-jni:+:all"
Fixed

2017-08-09 21:46 UTC, AustinShalit approved these changes

2017-09-30 14:45 UTC, PeterJohnson commented
No longer required due to #37 being merged.

2017-09-30 14:45 UTC, closed without merging